FROM node:latest

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/node_modules/.bin` to $PATH
ENV PATH /usr/src/node_modules/.bin:$PATH
ENV NODE_PATH /usr/src/node_modules;$NODE_PATH

# install and cache app dependencies
ADD package.json /usr/src/
RUN npm install --save /usr/src --silent
RUN npm install react-scripts@1.0.15 -g --silent

# start app
CMD ["npm", "start"]